<?php

error_reporting(E_ALL ^ E_NOTICE);
ini_set('display_errors', '1');
ini_set('apc.enabled', '0');

// Do not edit this file. Put your code inside of a theme.

include(dirname(__FILE__) . '/framework/head.php');
if(!file_exists(dirname(__FILE__) . '/theme/'.$theme.'.php')) {
	$theme = 'default';
}
include(dirname(__FILE__) . '/theme/'.$theme.'.php');
include(dirname(__FILE__) . '/framework/foot.php');
?>
